#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
  CONFIG_DIR='/etc/cardano'
  HOME_DIR='/var/lib/cardano'
  if ! getent passwd cardano >/dev/null; then
    # Defaults to create group=cardano, home=/home/cardano
    adduser --quiet --system --group --shell '/bin/bash' --home "${HOME_DIR}" cardano
  fi

  # make config directories if don't exist
  [ ! -d "${CONFIG_DIR}" ] && install -d -m 0750 -o root -g cardano "${CONFIG_DIR}"
  # private readable by cardano so cn-leaderlog script can read keys as cardano
  [ ! -d "${CONFIG_DIR}/private" ] && install -d -m 0750 -o root -g cardano "${CONFIG_DIR}/private"
  # Nb. home directory /var/lib/cardano created above with adduser command

  IOG_CONFIG_SRC='https://book.world.dev.cardano.org/environments'
  echo "Downloading configuration files"
  cd "${CONFIG_DIR}"
  for net in mainnet preprod preview; do
    for part in config topology byron-genesis shelley-genesis alonzo-genesis; do
      if [ -f "${net}-${part}.json" ]; then
        echo "  ${CONFIG_DIR}/${net}-${part}.json exists. Skipping."
      else
        echo -n "  ${CONFIG_DIR}/${net}-${part}.json ..."
        curl -sL "${IOG_CONFIG_SRC}/${net}/${part}.json" > "${net}-${part}.json"
	chgrp cardano "${net}-${part}.json"
	chmod 0640 "${net}-${part}.json"
        echo " saved."
      fi
    done
  done
  # Create basic etc/my-cardano-node-config.json file
  if [ -f 'my-cardano-node-config.json' ]; then
    echo "  ${CONFIG_DIR}/my-cardano-node-config.json exists. Skipping."
  else
    config="$(jq -n '{port: 3001, poolId: "#FIXME", pooltoolApiKey: "#FIXME", peers: []}')"
    echo "$config" > 'my-cardano-node-config.json'
    chgrp cardano 'my-cardano-node-config.json'
    chmod 0640 'my-cardano-node-config.json'
    echo "  ${CONFIG_DIR}/my-cardano-node-config.json. Created. Please edit as required."
  fi
fi

#DEBHELPER#

exit 0
